import type {
  StudentProfile, CompanyProfile, SchoolProfile,
  Opportunity, Application, Publication, Conversation,
  Skill, PortfolioEvidence
} from '@/types'

// ─── Student Profiles ─────────────────────────────────────────────────────────
export const mockStudents: StudentProfile[] = [
  {
    id: 'stu-1',
    userId: 'usr-1',
    user: { id: 'usr-1', email: 'matias@colegio.cl', role: 'STUDENT', createdAt: '2024-01-15', updatedAt: '2024-03-01', isActive: true },
    firstName: 'Matías',
    lastName: 'Arancibia',
    headline: 'Desarrollador Full Stack · 4° Año Informática',
    bio: 'Apasionado por el desarrollo web y la automatización. He trabajado con React, Node.js y bases de datos SQL en proyectos reales durante mi formación técnica.',
    specialty: 'Ingeniería Civil Informática',
    year: 4,
    gpa: 6.4,
    location: 'Santiago, Chile',
    avatar: '/avatars/matias.jpg',
    readinessScore: 82,
    profileViews: 42,
    skills: [
      { id: 'sk-1', name: 'React', category: 'TECNICA', level: 4, isValidated: true, validationStatus: 'VALIDADA', endorsements: 5, createdAt: '2024-02-01' },
      { id: 'sk-2', name: 'Node.js', category: 'TECNICA', level: 3, isValidated: true, validationStatus: 'VALIDADA', endorsements: 3, createdAt: '2024-02-01' },
      { id: 'sk-3', name: 'PostgreSQL', category: 'TECNICA', level: 3, isValidated: false, validationStatus: 'PENDIENTE', endorsements: 1, createdAt: '2024-02-15' },
      { id: 'sk-4', name: 'TypeScript', category: 'TECNICA', level: 3, isValidated: false, validationStatus: 'PENDIENTE', endorsements: 2, createdAt: '2024-02-20' },
      { id: 'sk-5', name: 'Trabajo en equipo', category: 'BLANDA', level: 5, isValidated: true, validationStatus: 'VALIDADA', endorsements: 8, createdAt: '2024-01-20' },
      { id: 'sk-6', name: 'Comunicación', category: 'BLANDA', level: 4, isValidated: false, validationStatus: 'PENDIENTE', endorsements: 4, createdAt: '2024-01-20' },
    ],
    evidences: [
      { id: 'ev-1', studentId: 'stu-1', title: 'Sistema de Gestión Escolar', description: 'Aplicación web para gestión de notas y asistencia usando React + Express + PostgreSQL.', type: 'PROYECTO', imageUrl: '/evidences/proyecto1.jpg', tags: ['React', 'Node.js', 'PostgreSQL'], isPublic: true, createdAt: '2024-01-10', updatedAt: '2024-01-10' },
      { id: 'ev-2', studentId: 'stu-1', title: 'Certificado AWS Cloud Practitioner', description: 'Certificación oficial de Amazon Web Services para fundamentos de nube.', type: 'CERTIFICADO', tags: ['AWS', 'Cloud'], isPublic: true, createdAt: '2024-02-20', updatedAt: '2024-02-20' },
      { id: 'ev-3', studentId: 'stu-1', title: 'API REST de e-commerce', description: 'Backend completo para plataforma de ventas con autenticación JWT y manejo de pagos.', type: 'PROYECTO', tags: ['Node.js', 'Express', 'JWT'], isPublic: true, createdAt: '2024-03-05', updatedAt: '2024-03-05' },
    ],
    validations: [],
    applications: [],
    createdAt: '2024-01-15',
    updatedAt: '2024-03-01',
  },
  {
    id: 'stu-2',
    userId: 'usr-2',
    user: { id: 'usr-2', email: 'lorena@colegio.cl', role: 'STUDENT', createdAt: '2024-01-15', updatedAt: '2024-03-01', isActive: true },
    firstName: 'Lorena',
    lastName: 'Ramírez',
    headline: 'Técnica en Redes · Especialista en Ciberseguridad',
    bio: 'Me interesa la seguridad de redes y los sistemas distribuidos. Actualmente trabajando en mi certificación CompTIA Security+.',
    specialty: 'Redes y Telecomunicaciones',
    year: 3,
    location: 'Santiago, Chile',
    avatar: '/avatars/lorena.jpg',
    readinessScore: 68,
    profileViews: 27,
    skills: [
      { id: 'sk-7', name: 'Cisco Networking', category: 'TECNICA', level: 4, isValidated: true, validationStatus: 'VALIDADA', endorsements: 6, createdAt: '2024-02-01' },
      { id: 'sk-8', name: 'Linux', category: 'TECNICA', level: 3, isValidated: false, validationStatus: 'PENDIENTE', endorsements: 2, createdAt: '2024-02-15' },
      { id: 'sk-9', name: 'Pensamiento crítico', category: 'BLANDA', level: 5, isValidated: true, validationStatus: 'VALIDADA', endorsements: 7, createdAt: '2024-01-20' },
    ],
    evidences: [],
    validations: [],
    applications: [],
    createdAt: '2024-01-15',
    updatedAt: '2024-03-01',
  },
]

// ─── Companies ────────────────────────────────────────────────────────────────
export const mockCompanies: CompanyProfile[] = [
  {
    id: 'comp-1',
    userId: 'usr-10',
    user: { id: 'usr-10', email: 'rrhh@techcorp.cl', role: 'EMPRESA', createdAt: '2024-01-01', updatedAt: '2024-03-01', isActive: true },
    name: 'TechCorp Chile',
    description: 'Empresa líder en desarrollo de software empresarial con presencia en toda Latinoamérica.',
    industry: 'Tecnología',
    size: '200-500 empleados',
    location: 'Santiago, Chile',
    website: 'https://techcorp.cl',
    logo: '/logos/techcorp.svg',
    opportunities: [],
    createdAt: '2024-01-01',
    updatedAt: '2024-03-01',
  },
  {
    id: 'comp-2',
    userId: 'usr-11',
    user: { id: 'usr-11', email: 'rrhh@redcloud.cl', role: 'EMPRESA', createdAt: '2024-01-01', updatedAt: '2024-03-01', isActive: true },
    name: 'RedCloud Solutions',
    description: 'Consultora de infraestructura cloud y ciberseguridad para empresas en transformación digital.',
    industry: 'Cloud & Seguridad',
    size: '50-200 empleados',
    location: 'Providencia, Santiago',
    website: 'https://redcloud.cl',
    logo: '/logos/redcloud.svg',
    opportunities: [],
    createdAt: '2024-01-01',
    updatedAt: '2024-03-01',
  },
]

// ─── Opportunities ────────────────────────────────────────────────────────────
export const mockOpportunities: Opportunity[] = [
  {
    id: 'opp-1',
    companyId: 'comp-1',
    company: mockCompanies[0],
    title: 'Pasantía Desarrollador Frontend',
    description: 'Buscamos estudiantes de último año de Informática para integrarse a nuestro equipo de producto. Trabajarás en aplicaciones React con TypeScript en un ambiente ágil.',
    type: 'PASANTIA',
    location: 'Santiago',
    isRemote: false,
    salary: '$450.000 - $600.000 CLP',
    requirements: ['Manejo de React', 'Git básico', 'Comunicación efectiva'],
    skills: ['React', 'TypeScript', 'Git'],
    specialty: 'Informática',
    deadline: '2024-04-30',
    isActive: true,
    applicantsCount: 12,
    matchScore: 88,
    createdAt: '2024-03-15',
    updatedAt: '2024-03-15',
  },
  {
    id: 'opp-2',
    companyId: 'comp-2',
    company: mockCompanies[1],
    title: 'Práctica Técnico en Redes',
    description: 'Únete a nuestro equipo de infraestructura cloud. Aprenderás sobre AWS, redes empresariales y herramientas de monitoreo en proyectos reales.',
    type: 'PRACTICA',
    location: 'Providencia, Santiago',
    isRemote: true,
    salary: '$400.000 CLP',
    requirements: ['Fundamentos de redes', 'Linux básico', 'Proactividad'],
    skills: ['Cisco Networking', 'Linux', 'AWS'],
    specialty: 'Redes',
    deadline: '2024-05-15',
    isActive: true,
    applicantsCount: 8,
    matchScore: 65,
    createdAt: '2024-03-10',
    updatedAt: '2024-03-10',
  },
  {
    id: 'opp-3',
    companyId: 'comp-1',
    company: mockCompanies[0],
    title: 'Desarrollador Backend Junior',
    description: 'Posición de trabajo para recién egresados. Buscamos alguien con conocimiento en Node.js, bases de datos y APIs REST.',
    type: 'TRABAJO',
    location: 'Santiago',
    isRemote: false,
    salary: '$800.000 - $1.000.000 CLP',
    requirements: ['Node.js', 'PostgreSQL', 'API REST', 'Trabajo en equipo'],
    skills: ['Node.js', 'PostgreSQL', 'TypeScript'],
    deadline: '2024-06-01',
    isActive: true,
    applicantsCount: 34,
    matchScore: 74,
    createdAt: '2024-03-01',
    updatedAt: '2024-03-01',
  },
]

// ─── Applications ─────────────────────────────────────────────────────────────
export const mockApplications: Application[] = [
  {
    id: 'app-1',
    studentId: 'stu-1',
    opportunityId: 'opp-1',
    opportunity: mockOpportunities[0],
    status: 'EN_REVISION',
    coverLetter: 'Estoy muy interesado en esta oportunidad...',
    createdAt: '2024-03-20',
    updatedAt: '2024-03-21',
  },
  {
    id: 'app-2',
    studentId: 'stu-1',
    opportunityId: 'opp-3',
    opportunity: mockOpportunities[2],
    status: 'PENDIENTE',
    createdAt: '2024-03-18',
    updatedAt: '2024-03-18',
  },
  {
    id: 'app-3',
    studentId: 'stu-1',
    opportunityId: 'opp-2',
    opportunity: mockOpportunities[1],
    status: 'ENTREVISTA',
    createdAt: '2024-03-10',
    updatedAt: '2024-03-22',
  },
]

// ─── Publications ─────────────────────────────────────────────────────────────
export const mockPublications: Publication[] = [
  {
    id: 'pub-1',
    authorId: 'stu-2',
    authorType: 'STUDENT',
    authorName: 'Lorena Ramírez',
    authorAvatar: '/avatars/lorena.jpg',
    authorSchool: 'Instituto Técnico Metropolitano',
    content: '¡Terminé mi proyecto de redes! Diseñé una infraestructura completa con VLANs, redundancia y monitoreo centralizado. 3 meses de trabajo que valieron totalmente la pena 💪',
    imageUrl: '/publications/redes-proyecto.jpg',
    isStory: false,
    likes: 24,
    comments: 6,
    views: 148,
    isLiked: false,
    tags: ['Redes', 'VLAN', 'Proyecto'],
    createdAt: '2024-03-22T10:30:00Z',
    updatedAt: '2024-03-22T10:30:00Z',
  },
  {
    id: 'pub-2',
    authorId: 'school-1',
    authorType: 'COLEGIO',
    authorName: 'Instituto Técnico Metropolitano',
    authorAvatar: '/logos/colegio.svg',
    content: '🎉 Feria de Empleabilidad 2024 — Más de 30 empresas del sector tecnológico estarán presentes. Inscríbete antes del 10 de abril y prepara tu perfil en Red Talento.',
    isStory: false,
    likes: 87,
    comments: 14,
    views: 532,
    isLiked: true,
    tags: ['FeriaEmpleabilidad', 'Oportunidades'],
    createdAt: '2024-03-20T09:00:00Z',
    updatedAt: '2024-03-20T09:00:00Z',
  },
  {
    id: 'pub-3',
    authorId: 'stu-1',
    authorType: 'STUDENT',
    authorName: 'Matías Arancibia',
    authorAvatar: '/avatars/matias.jpg',
    authorSchool: 'Instituto Técnico Metropolitano',
    content: 'Acabo de obtener mi certificación AWS Cloud Practitioner. Si alguien quiere consejos para prepararse, con gusto les cuento cómo estudié 🙌',
    isStory: false,
    likes: 41,
    comments: 9,
    views: 203,
    isLiked: false,
    tags: ['AWS', 'Certificacion', 'Cloud'],
    createdAt: '2024-03-19T14:20:00Z',
    updatedAt: '2024-03-19T14:20:00Z',
  },
]

// ─── Stories (short-form) ─────────────────────────────────────────────────────
export const mockStories = [
  { id: 'st-1', authorId: 'stu-2', authorName: 'Lorena R.', authorAvatar: '/avatars/lorena.jpg', hasSeen: false },
  { id: 'st-2', authorId: 'stu-3', authorName: 'Carlos M.', authorAvatar: '/avatars/carlos.jpg', hasSeen: false },
  { id: 'st-3', authorId: 'stu-4', authorName: 'Ana Sofía', authorAvatar: '/avatars/ana.jpg', hasSeen: true },
  { id: 'st-4', authorId: 'school-1', authorName: 'ITM', authorAvatar: '/logos/colegio.svg', hasSeen: true },
  { id: 'st-5', authorId: 'stu-5', authorName: 'Pedro V.', authorAvatar: '/avatars/pedro.jpg', hasSeen: false },
]

// ─── Conversations ────────────────────────────────────────────────────────────
export const mockConversations: Conversation[] = [
  {
    id: 'conv-1',
    participantId: 'usr-10',
    participantName: 'TechCorp Chile — RRHH',
    participantAvatar: '/logos/techcorp.svg',
    participantRole: 'EMPRESA',
    lastMessage: 'Hola Matías, vimos tu perfil y nos interesa mucho tu experiencia en React.',
    lastMessageAt: '2024-03-22T11:30:00Z',
    unreadCount: 2,
    messages: [
      { id: 'msg-1', senderId: 'usr-10', receiverId: 'usr-1', content: 'Hola Matías, vimos tu perfil y nos interesa mucho tu experiencia en React.', isRead: false, createdAt: '2024-03-22T11:30:00Z' },
    ],
  },
  {
    id: 'conv-2',
    participantId: 'school-usr',
    participantName: 'Coordinación Instituto Técnico',
    participantAvatar: '/logos/colegio.svg',
    participantRole: 'COLEGIO',
    lastMessage: 'Recuerda completar tu portafolio antes de la feria del 15 de abril.',
    lastMessageAt: '2024-03-21T08:00:00Z',
    unreadCount: 0,
    messages: [],
  },
]

// ─── Current logged-in student (mock session) ─────────────────────────────────
export const currentStudent = mockStudents[0]

// ─── School Profile ───────────────────────────────────────────────────────────
export const mockSchool: SchoolProfile = {
  id: 'school-1',
  userId: 'school-usr',
  user: { id: 'school-usr', email: 'admin@itm.cl', role: 'COLEGIO', createdAt: '2023-01-01', updatedAt: '2024-03-01', isActive: true },
  name: 'Instituto Técnico Metropolitano',
  description: 'Formando líderes técnicos desde 1985. Somos el colegio técnico profesional con mayor tasa de empleabilidad de la región.',
  location: 'Santiago, Región Metropolitana',
  website: 'https://itm.cl',
  logo: '/logos/colegio.svg',
  specialties: ['Informática', 'Redes y Telecomunicaciones', 'Electrónica', 'Mecánica Industrial', 'Administración'],
  students: mockStudents,
  createdAt: '2023-01-01',
  updatedAt: '2024-03-01',
}
